# make services used in testing public
services:
    _defaults:
        autowire: true
        autoconfigure: true 
        public: true

    App\Core\Application\SourceAccess\SourceQuery\Factory\SourceDbSourceQueryFactory: ~